### ISSUE TITLE
Installation works but xenforo command throws error

### ISSUE THREAD

**Issue by mmeierer** [TUVIMEN/xenforo#1]
Thanks for providing this script.

The installation works fine as it was straightforward to follow your instructions.

However, when calling the command `xenforo`, e.g. `xenforo -h`, I get the following error message:
```
/usr/bin/xenforo: line 8: syntax error near unexpected token `newline'
/usr/bin/xenforo: line 8: `<!DOCTYPE html>'
```

Here is a Google Colab notebook to replicate this: [Link](https://colab.research.google.com/drive/1YH2DWsiUEQf1r5stzzW8amhEDKgll2S-?usp=sharing) 

Any guidance is greatly appreciated.

**Comment by TUVIMEN** [comment]
I believe you are using wrong url and just downloading html. Try using https://raw.githubusercontent.com/TUVIMEN/xenforo/master/xenforo instead of https://github.com/TUVIMEN/xenforo/blob/master/xenforo

**Comment by mmeierer** [comment]
My bad. Thanks for the quick response and pointing me to this oversight..
