### ISSUE TITLE
Scraping of posts seems not to work in specific situations (i.e., image at the beginning of post?)

### ISSUE THREAD

**Issue by mmeierer** [TUVIMEN/xenforo#4]
I had the time to put your script further to the test and it worked very well. 

A minor issue that I came across is the following:

There are few occasions where the scraping of forum posts does not work. Here are some exemplary links where **the slot “posts” in the resulting JSON file remains empty**:

- https://www.watchuseek.com/threads/gold-for-hublot-ambassador-usain-bolt.5209523/
- https://www.watchuseek.com/threads/baselworld-2016-hublot-live-report.5210059/
- https://www.watchuseek.com/threads/hublot-big-bang-sang-bleu.5210184/ 
- https://www.watchuseek.com/threads/hublot-big-bang-broderie-sugar-skull.5209923/ 
- https://www.watchuseek.com/threads/hublot-big-bang-unico-usain-bolt.5210349/

To give a quickly replicable example:  

Executing the command:

`xenforo -N 'https://www.watchuseek.com/threads/gold-for-hublot-ambassador-usain-bolt.5209523/'`

results in a JSON like this:

`{"link":"https://www.watchuseek.com/threads/gold-for-hublot-ambassador-usain-bolt.5209523/","id":"5209523","title":"Gold for Hublot Ambassador Usain Bolt","user_id":"","user":"","date":"","path":"Home/Forums/Watch Brands/Hublot/","tags":[],"poll":{"title":"","answers":[]},"posts":[]}
`

Could it be that the image at the very beginning of the post is the reasons for this? At least, this seems to be a shared characteristic of the posts where this issue occurs.

**Comment by TUVIMEN** [comment]
Those are articles, normally posts are in article tag but the first one in those threads is in div with "california-article-post california-message" class. They cannot be grabbed universally and would require posts to have .author .hero-image-wrapper fields.

Furthermore i have found some kind of auction [threads](https://www.watchuseek.com/threads/fs-sinn-356-flieger-ii-sa-copper-salmon-dial-lnib.5472586/) and they work similarly but have "california-article-post california-message california-listing-post" class. To the above fields they would also require .user-info .location .gallery and .price. Posts under the first one are even called replies.

I think that the only solution to download them fully would be to create -m option that would specify modifications. Unfortunately i don't know which mods add those features.

**Comment by mmeierer** [comment]
Makes sense. As I came across this yesterday, I wanted to mention it at least. While it was clear to me that the initial posts are "articles", the general structure looked to me very much like a regular thread.

Sorry, for hijacking this thread but let me quickly ask another question: 
Does downloading entire forums still work you? Yesterday it worked perfectly fine, but as of today, I only get the first threads (depending on how I set the number of processes). Then, the routine gets stuck,  

Like so (no matter if using the command locally or in an cloud-hosted notebook);
![image](https://user-images.githubusercontent.com/5850777/220680111-13b609d8-6331-4e41-a675-9b0606837381.png)

**Comment by TUVIMEN** [comment]
The script accidentally gets pinned threads links two times, since 1 thread already makes the file the other just prints the link and continues to other threads.

The script downloads the entire forum but the first threads have a lot of pages so it seems as if the script is stuck.
Actually a lot of time is being devoted to downloading reactions to posts so i think i will add option to ignore them as they are not that useful.

**Comment by mmeierer** [comment]
> Actually a lot of time is being devoted to downloading reactions to posts so i think i will add option to ignore them as they are not that useful.

That sounds like a very useful option.

**Comment by TUVIMEN** [comment]
The -n option has been [added](https://github.com/TUVIMEN/xenforo/commit/4d56b70907be0c2d7492612bea59b3418c52e3b6).

**Comment by mmeierer** [comment]
This option works. Great. 

Unfortunately, it does not seem to solve the above mentioned problem. 

However, as this is out of scope of this thread, I am going to investigate this further and try to come up with examples where it works and where it doesn't (and detail them in a dedicated issue thread) - hoping that this helps to pinpoint what happens under the hood.
