### ISSUE TITLE
Getting hgrep error or no results

### ISSUE THREAD

**Issue by ffcruz85** [TUVIMEN/xenforo#5]
Hi there, I am having a little trouble here and was hoping to get some help. I installed hgrep and jq through my package manager (I am using Manjaro Linux) and then proceeded with the sample commands here after running the install command you mention on the readme. I first tried to just run it without any arguments for a particular forum, as such:

`xenforo 'https://www.speedsolving.com/forums/forum-competitions.17/'`

That gave me the following error:

```
error: unexpected argument '-E' found

  note: to pass '-E' as a value, use '-- -E'

Usage: hgrep [FLAGS] [OPTIONS] [PATTERN [PATH...]]

For more information, try '--help'.
```

Since I am not familiar with xenforo and just doing this for a research project, I figured maybe this forum was in the old format you mention, so I also tried this:

`xenforo -o 'https://www.speedsolving.com/forums/forum-competitions.17/'`

In that case, no output came out on the terminal at all, but also, nothing no files were produced in the current directory...

I assume I am doing something stupid here - but could you give me any insights?

Thanks!

**Comment by TUVIMEN** [comment]
Manjaro repository provides rusted version of grep with highlights - (hgrep)[https://github.com/rhysd/hgrep]. You should uninstall it and compile html parsing hgrep from [here](https://github.com/rhysd/hgrep).

Also old format refers to 1.X xenforo version, your example is 2.X so there will be no output by using it.

**Comment by ffcruz85** [comment]
Thank you! I think I went for the package because I had some issue building it, but I don't remember. I tried again, but this time I was on a windows PC and running it in WSL2 Ubuntu, and both building hgrep and using the xenforo scraper worked just fine on that platform. I will let you know if I see any issues back in manjaro - but I am all set, thanks for your help.
