### ISSUE TITLE
Ignore unsupported /link-forum/ links

### ISSUE THREAD

**Issue by SvicidalBug** [TUVIMEN/xenforo#6]
I've encountered a forum which includes /link-forums/ links within it's subforum listings. These links redirect back to the root subforum listings and append a scroll anchor to the URL. The script doesn't seem to know how to handle this and gets stuck in a loop.

```
$ xenforo --max-procs 4 --no-reactions --no-users --category https://www.vwvortex.com/forums/
https://www.vwvortex.com/link-forums/audi-marketplace.5654/

https://www.vwvortex.com/link-forums/audi-marketplace.5654/

https://www.vwvortex.com/link-forums/audi-marketplace.5654/

https://www.vwvortex.com/link-forums/audi-marketplace.5654/
```

**Comment by TUVIMEN** [comment]
This issue has been solved in [this commit](https://github.com/TUVIMEN/xenforo/commit/b7501096f20f270531ff684afd33bf7b93b8a726) by ignoring /link-forums/.* links.
